### ISSUE TITLE
Tutor received wrong notification after student accepted on agreement

### ISSUE THREAD

**Issue by ycphuah** [D0019208/Service-Loop#45]
When the student accepted the agreement, student received a notification stating that the student has accepted the agreement offered by tutor "name". Tutor also received the exact same notification as this one, while it should be the student "name" has accepted agreement. 

The notification is fixed when tutor reload the app. It will show the correct notification instead of the one received by student.

**Comment by ycphuah** [comment]
Nichita: My guess is that we update the notifications with the wrong notification. So instead of showing the tutor notification we are showing the student notification.

**Comment by D0019208** [comment]
All fixed
